reactjs/react-a11y

package.json

Forgot to update the republish script to use Babel over 6to5

Use Babel for prepublish

---

lib/__tests__/index-test.js
lib/assertions.js

onKeyUp is too late to prevent space from scrolling the browser, so it
should be onKeyDown.
While I was doing this I clarified the `BUTTON_ROLE_*` rule names and set
`BUTTON_ROLE_ENTER` to account for `onKeyUp` or `onKeyDown`

[fixed] Button role didn't allow onKeyDown

---

.gitignore
lib/__tests__/index-test.js
lib/index.js

This PR restructures assertAccessibility so that when an element fails it can add a unique `id` (if one doesn't already exist) and logs it in the message.
#a11y-0 You have an anchor with `href="#"` and no `role` DOM property. Add `role="button"` or better yet, use a `<button/>`.
`document.getElementById('a11y-0')` will show me the element that is failing. Then with `Reveal in Elements Panel` (Chrome's terminology) you can track down where it is.
Closes #11 
Closes #9
This is a better solution as it marks all of your elements so you can find them. No need to guess based on a stack or logging the props.

Mark all failing tags with an ID and include it in the message

---

README.md
lib/__tests__/index-test.js
lib/assertions.js
lib/index.js
package.json

With this PR instead of `react-a11y` requiring React directly, you just pass your own React in.
```
var React = require('react');
var a11y = require('react-a11y');
if (ENV === 'development') a11y(React)
```
Closes https://github.com/rackt/react-a11y/pull/23
Closes https://github.com/rackt/react-a11y/pull/18
Fixes https://github.com/rackt/react-a11y/issues/16
Note: This and all of my other PRs are available with `npm install @asaayers/react-a11y`
[@asaayers/react-a11y](https://www.npmjs.com/package/@asaayers/react-a11y)

Drop React from peerDependency and rely on passing it in.

---

.travis.yml
CONTRIBUTING.md
README.md
karma.conf.js
lib/__tests__/index-test.js
lib/after.js
lib/assertions.js
lib/index.js
package.json
tests.webpack.js
webpack.config.js

[fixed] Issue where label assertion returns a false negative when label is inside a child Component (fixes #44)
[added] Tests to ensure anchors with a tabIndex but without an href require an ARIA button role (fixes #45)
[added] selection and option to the list of interactive elements that require labels
[removed] getFailures() method since all failures are now logged asynchronously

Fixes for issue #44 and #45

---

lib/__tests__/index-test.js
lib/assertions.js

[fixed] issue where elements with the presentation role required a label. resolves #50

Elements with a role of presentation should not require a label

---

lib/__tests__/index-test.js
lib/assertions.js
lib/index.js

[fixed] bug where placeholder links required a tabindex and an ARIA role (closes #62)
[fixed] bug where elements with role=none required a label (closes #63)
[fixed] bug where elements with aria-hidden required a label (closes #64)
[added] test to ensure interactive elements hidden using aria-hidden are removed from the tab flow

Lots of bug fixes

---

lib/__tests__/index-test.js
lib/index.js

warningPrefix allows one to specify an optional prefix to be added
to the failure message.
This allows us to filter out just the react-a11y errors from our console log.
Thanks,
Matt and Caroline

[added] warningPrefix option

---

lib/__tests__/index-test.js
lib/assertions.js

We modified the redundant alt rule to include a check for "picture". This is a rule we wanted for our own project and it seemed in line with the existing rule.
Please let us know if you have any questions or concerns
Thanks,
Matt and Kenny

[added] "picture" to the list of redundant words in img[alt]

---

lib/__tests__/index-test.js
lib/assertions.js

Correctly accounts for use of the aria-labelledby attribute.

[fixed] correctly accounting for aria-labelledby (resolves #87)

---

lib/__tests__/index-test.js
lib/assertions.js
lib/index.js

We were having an issue with the way children was being passed into tests. We're using react-bootstrap, which creates some links the following way:
```js
React.createElement('a', {href: 'some-href', children: 'stuff'})
```
This was giving us 'no label' errors when it should have been fine. This is because the code previously expected that `children` would be passed down as the 3rd+ argument of React.createElement.

Children fix

---

lib/index.js

In React 0.14, props are frozen. Because of this, we have to create a new props object to pass react-a11y ids along.
Long term, it would be nice (and would solve a lot of issues) if react-a11y didn't generate IDs at all. Until then, this will keep it running smoothly in React 0.14.

React 0.14 Compatibility: Create new props object instead of mutating existing one

---

karma.conf.js
lib/assertions.js
lib/index.js
package.json
webpack.config.js

Removes babel-runtime
Replaces Set usage with Array
Replaces Object.assign usage with object.assign module
I'm hoping to have this merged so that we don't need to include `babel-runtime` as a peer dependency, because we don't use `babel-runtime` and it could lead to a differences in test and production environments. 
Addresses https://github.com/reactjs/react-a11y/issues/76

Remove babel-runtime

---

README.md
lib/__tests__/index-test.js
lib/assertions.js
lib/index.js
package.json

Adds support for a `ReactDOM` key in the options hash, and uses that if provided, thereby maintaining 0.13 and 0.14 compatibility.
```js
import React from 'react';
import ReactDOM from 'react-dom';
import a11y from 'react-a11y';
a11y(React, { ReactDOM });
```
Fixes deprecation warnings from React.render and React.findDOMNode.
Future-proofs `react-a11y` for React 0.15
I'm hoping to have this merged because our build steps fails on any `console.warn`s, and I'd rather fix the issue than whitelist the `findDOMNode` warning

Update to use ReactDOM

---

README.md
lib/index.js
package.json
webpack.config.js

This fixes the Travis build status badge and replaces all references to Rackt with ReactJS as per https://github.com/reactjs/react-a11y/issues/109

Replace references to Rackt with ReactJS

---

package.json

because why did I even not make it a dependency in the first place

[fixed] Move object.assign from devDeps to deps (resolves #115)

---

README.md
lib/__tests__/index-test.js
lib/after.js
lib/index.js

`a11y` patches the `React.createElement` method, and sometimes
patches lifecycle events of components. This adds a `restoreAll`
method to `a11y` which cleans up after itself.
This is particularly useful for using `React-a11y` in JavaScript
test suites, where the patched `React` and/or components may be
reused in future tests.
cc @kloots who originally extracted `after`

[added] a11y.restoreAll() method to clean up mutations to React

---

lib/__tests__/index-test.js
lib/assertions.js

We were getting false fails for "unlabeled inputs" that have `type="submit"` and a `value` attribute. These are valid inputs. This PR changes it so it will only throw a violation for inputs that have `type="submit"` but no `value` attribute.

Don't throw violations for valid inputs with type="submit"

---

README.md

Small documentation improvement to reflect it should always be passed. Any use of `ReactDOM.findDOMNode` for example will result in errors when `ReactDOM` is not passed as `setReact` is defaulting to `React` which no longer has that function.

[doc] always include ReactDOM as option for React >= 0.14

---

src/rules/button-role-space.js

Allow onKeyPress as well as onKeyDown for role="button".
Some documents prefer keypress over keydown:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role

Allow onKeyPress as well as onKeyDown for button

---

.eslintrc
docs/rules/tabindex-no-positive.md
docs/rules/tabindex-uses-button.md
src/rules/index.js
src/rules/tabindex-no-positive.js

Addresses Issue #66 .  This rule was actually added with v1.0.0 but due to the rule documentation missing I didn't realize it to close the issue earlier.
- Renamed rule avoid-positive-tabindex to tabindex-no-positive to be more inline with the rule naming in eslint-plugin-jsx-a11y.
- Added documentation for rule that had been missing.

Fix for issue #66

---

README.md

Thanks for the awesome package!
After I add the package, and add demo codes, I got the warning immediately. I thought I did something wrong.
> [react-a11y]: Warning: the rule redundant-alt is deprecated.  Use the rule img-redundant-alt instead.
Then I found I need upgrade the codes based on the migration. I feel it might provide a better experience to just let user use new rule directly : )

doc: upgrade to new rule in demo

---

README.md

Fixes #177 
[react-axe](https://github.com/dequelabs/react-axe) has been deprecated in a move to [@axe-core/react](https://github.com/dequelabs/axe-core-npm/tree/develop/packages/react). I discovered this when I visited the current link and then had to follow the second deprecation link on react-axe. I updated the package name and link in this readme so future engineers would be saved a step.

Updated deprication warning to use link to new repo for @axe-core/react
